data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: true
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling:
      - 0.5
      - 1.25
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: true
    normalize_images: true
device: auto
inference:
  multithreading:
    enabled: true
    queue_length: 4
    timeout: 30.0
  compile:
    enabled: false
    backend: inductor
  autocast:
    enabled: false
metadata:
  project_path: D:\pycode\DeepLabCut\Testcore-Mackenzie-2025-11-04
  pose_config_path: 
    D:\pycode\DeepLabCut\Testcore-Mackenzie-2025-11-04\dlc-models-pytorch\iteration-0\TestcoreNov4-trainset80shuffle1\train\pytorch_config.yaml
  bodyparts:
  - bodypart1
  - bodypart2
  - bodypart3
  - objectA
  unique_bodyparts: []
  individuals:
  - animal
  with_identity:
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: false
    freeze_bn_weights: false
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: false
        clip_scores: true
        location_refinement: true
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 4
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: false
        generate_locref: true
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels:
        - 2048
        - 4
        kernel_size:
        - 3
        strides:
        - 2
      locref_config:
        channels:
        - 2048
        - 8
        kernel_size:
        - 3
        strides:
        - 2
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus:
  key_metric: test.mAP
  key_metric_asc: true
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list:
      - - 0.0001
      - - 1e-05
      milestones:
      - 90
      - 120
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: false
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: false
  display_iters: 2
  epochs: 3
  seed: 42
